winners = {1: 'CDS MARMALADE'}
winners[2] = 'Memeinator'
winners[3] = ' '
winners[4] = ' '
winners[5] = ' '
winners[6] = ' '
winners[7] = ' '
winners[8] = ' '
winners[9] = ' '
winners[10] = ' '
winners[11] = ' '
winners[12] = ' '
winners[13] = ' '
winners[14] = ' '
winners[15] = ' '
print(winners)
